#!/bin/bash
set -e

./build-web $@

echo "building full"
typedoc --name "KRC-721 WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/krc721 ./build/docs/krc721.ts
